<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php
            echo ('Salutare! ' .$variable);
        ?>
        <div>Formular de inregistrare:</div>
        <form action="world" method="post">
            <div><input type="text" name="name" placeholder= "Name"></div>
            <div><input type="text" name="age" placeholder="Age"></div>
            <div><input type="email" name="email" placeholder="Email"></div>
            <div><input type="password" name="password" placeholder="Password"></div>
            <div><input type="submit" name="Submit" style="margin-top:10px;"></div>
        </form>
        <?php foreach($users as $user) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->name);?></td>
            
            </tr>
        <?php endforeach;?>
        
    </body>
</html>
