<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php
            echo ('Salutare! ' .$variable);
            
        $title = 'Formular de inregistrare:';
        $this->headTitle($title);
        ?>
        <h3><?php echo $this->escapeHtml($title);?></h3>

        <?php
            //echo $this->form($form);
            $form = $this->form;
//            $form->setAttribute('action', $this->url(
//                    'hello',
//                    array(
//                        'action' => 'world'
//                    )
//            ));
            $form->prepare();
            
            echo $this->form()->openTag($form);
            //echo $this->formHidden($form->get('id'));?>
            <div><?php echo $this->formRow($form->get('name')); ?></div>
            <div><?php echo $this->formRow($form->get('age'));?></div>
            <div><?php echo $this->formRow($form->get('email'));?></div>
            <div><?php echo $this->formRow($form->get('password'));?></div>
            <?php echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
         ?>
        <?php 
            foreach($errors as $error)
            {
                echo $this->escapeHtml($error);
            }
        ?>
        <br>
        <table border="1">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Age</td>
                    <td>Email</td>
                </tr>
            </thead>
        <?php foreach($users as $user) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->name);?></td>
                <td><?php echo $this->escapeHtml($user->age);?></td>
                <td><?php echo $this->escapeHtml($user->email);?></td>
            </tr>
        <?php endforeach;?>
        </table>
       
       <?php echo $this->escapeHtml($check->name);?>
    </body>
</html>
